### ISSUE TITLE
fillAlpha property ignored or not behaving the same as VectorDrawable

### ISSUE THREAD

**Issue by KennyGoers** [alexjlockwood/kyrie#14]
This may be known, but I didn't see it anywhere. The "fillAlpha" property in a path appears to be ignored in the Kyrie drawable. with the fillColor set to a non-transparent color the VectorDrawable "correctly" utilizes the "fillAlpha" of the path, while the KyrieDrawable appears to ignore it.

**Comment by KennyGoers** [comment]
To clarify, this is only when loaded from a vector drawable resource, it works as expected when using a builder to create the drawable.

**Comment by alexjlockwood** [comment]
Ahh, it wasn't known. Thanks for reporting!

I really hate the way Android attrs work sometimes... :|

I'm planning on publishing a new release sometime in the next week so this should be out relatively soon.

**Comment by KennyGoers** [comment]
Easy fix at least! I'll probably end up building all mine from scratch with the builder, I'll be abusing er I mean using Kyrie for a lot of static and animated vectors as I build a custom map layer/view for animated map markers, been using your shape shifter, but I need to set the path colors manually so wont be able to use the output of that directly... Thanks for the library, I really didn't want to write one myself

**Comment by alexjlockwood** [comment]
If all you need to modify is a path's fill/stroke color... there are sometimes ways you can kinda workaround this using `VectorDrawableCompat#setTint()`. Tinting the vector will modify the color of the entire drawable... which may not be what you want. But what you could possibly do is split the `VectorDrawable` into multiple `VectorDrawable`s (i.e. one for each path that you need to modify dynamically)... and then tint them individually w/ whatever color you want... and then put them all in a `LayerDrawable` so that they overlap on top of each other to create the same visual result.

**Comment by KennyGoers** [comment]
thanks for the pointers, the tint won't work as I need to set the border (stroke) color to something other than the tint, hoping to add gradients at some point, but that isn't important right now. 
I thought of the layered drawable part for the static images, but I need to transition markers to selected/normal/in-motion using animated vectors [kyrie ;)] for that so it will be easier to just add a module that has methods to create the drawables

**Comment by alexjlockwood** [comment]
Ahh yeah... that is another thing I need to write for Kyrie... gradient support (which is coming to `VectorDrawableCompat` soon as well, yay!)
